name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test
      # cp -r prayer-global-porch.php includes languages spinner.svg version-control.json LICENSE SECURITY.md prayer-global-porch/
      # Below borrowed from https://github.com/actions/upload-release-asset
      #
      - name: Update package.json
        run: |
          sed -i 's/"version": ".*"/"version": "${{ github.ref }}"/' package.json

      - name: Update version-control.json
        run: |
          sed -i 's/"version": ".*"/"version": "${{ github.ref }}"/' version-control.json
          date=$(git log --tags --simplify-by-decoration --pretty="format:%ci %d" | grep -P '${{ github.ref }}[^.]' | awk '{ print $1, $2 }')
          sed -i "s/\"last_updated\": \".*\"/\"last_updated\": \"$date\"/" version-control.json

      - name: Build project
        run: |
          mkdir prayer-global-porch
          cp -r prayer-global-porch.php api charts classes pages post-type redirects support version-control.json LICENSE SECURITY.md prayer-global-porch/
          zip -r prayer-global-porch.zip prayer-global-porch
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./prayer-global-porch.zip
          asset_name: prayer-global-porch.zip
          asset_content_type: application/zip

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: Release v${{ github.ref }}"

